version: "2.2"

services:
  mariadb:
    image: mariadb
    networks:
        - backend
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=P@55word
      - MYSQL_USER=user
      - MYSQL_PASSWORD=P@55word
      - MYSQL_DATABASE=projetJEE2022
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
  webpage:
    build: .
    networks:
        - backend
    ports:
        - "8080:8080"

networks:
    backend:
        driver: bridge
